"""add_performance_rating_field

Revision ID: a9f0896eb3bc
Revises: 
Create Date: 2026-02-07 16:44:37.936548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a9f0896eb3bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_traces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_observations', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('quality_metrics', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('agent_context', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('performance_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('complexity_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('efficiency_score', sa.Float(), nullable=True))
        batch_op.alter_column('context',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('success',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('complexity_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('agent_involved', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('validation_results', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('performance_metrics', sa.JSON(), nullable=True))
        batch_op.alter_column('parameters',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('parameters',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.drop_column('performance_metrics')
        batch_op.drop_column('validation_results')
        batch_op.drop_column('agent_involved')
        batch_op.drop_column('complexity_level')
        batch_op.drop_column('quality_score')

    with op.batch_alter_table('execution_traces', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('success',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('context',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.drop_column('efficiency_score')
        batch_op.drop_column('complexity_score')
        batch_op.drop_column('performance_score')
        batch_op.drop_column('agent_context')
        batch_op.drop_column('quality_metrics')
        batch_op.drop_column('agent_observations')

    # ### end Alembic commands ###
